# Page settings
baseurl = "http://www.atom.im/"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

[params]
# Meta
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu WAN"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected Call for Papers in computer architecture & system fields."

# Highlight section
[params.highlight]
enable = true
title = "Highlight"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
#final = "Final Version"
countdown = "Countdown" # yyyy/mm/dd hh:mm (Asia/Shanghai)

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming Calls"
year = "2019"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Active Calls"
year = "2018"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# past section
[params.past]
enable = true
title = "Past Calls"
year = "2018"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# [ONE] highlight item
[[params.highlight.list]]
enable = 1
confname = "NVMSA 2018"
confsite = "https://nvmsa18.github.io"
when = "Aug 28-31, 2018"
absddl = "Apr 20, 2018"
submddl = "Apr 27, 2018"
notidue = "Jun 1, 2018"
countdown = "2018/8/28 00:00"

[[params.past.list]]
enable = -1
confname = "ASPLOS"
confsite = "https://asplos-conference.org/"
when = "Apr 13-17, 2019"
absddl = "Jul 31, 2018"
submddl = "Aug 7, 2018"
notidue = "Nov 7, 2018"
countdown2ddl = "2018/7/31"
countdown2event = "2019/4/13"

[[params.upcoming.list]]
enable = 1
confname = "FAST"
confsite = "https://www.usenix.org/conference/fast19/call-for-papers"
when = "Feb 25-28, 2019"
absddl = "N/A"
submddl = "Sep 26, 2018"
notidue = "Dec 11, 2018"
countdown2ddl = "2018/9/26"
countdown2event = "2019/2/25"

[[params.past.list]]
enable = 1
confname = "HPCA"
confsite = "http://hpca2019.seas.gwu.edu/"
when = "Feb 16-20, 2019"
absddl = "Jul 27, 2018"
submddl = "Aug 3, 2017"
notidue = "Nov 6, 2017"
countdown2ddl = "2018/7/27"
countdown2event = "2019/2/16"

[[params.past.list]]
enable = -1
confname = "ISCA"
confsite = "http://isca2018.ece.ucr.edu/"
when = "Jun 2-6, 2018"
absddl = "Nov 14, 2017"
submddl = "Nov 21, 2017"
notidue = "Mar 13, 2018"
countdown2ddl = "2018/6/2"
countdown2event = "2018/6/2"

[[params.past.list]]
enable = -1
confname = "MICRO"
confsite = "https://www.microarch.org/micro51/"
when = "Oct 20-24, 2018"
absddl = "Mar 30, 2018"
submddl = "Apr 6, 2018"
notidue = "Jul 18, 2018"
countdown2ddl = "2018/10/20"
countdown2event = "2018/10/20"

[[params.past.list]]
enable = -1
confname = "SC"
confsite = "https://sc18.supercomputing.org/submit/submission-deadlines/"
when = "Nov 11-16, 2018"
absddl = "Mar 19, 2018"
submddl = "Mar 26, 2018"
notidue = "Jun 15, 2018"
countdown2ddl = "2018/11/11"
countdown2event = "2018/11/11"

[[params.past.list]]
enable = -1
confname = "USENIX ATC"
confsite = "https://www.usenix.org/conference/atc18/call-for-papers"
when = "Jul 11-13, 2018"
absddl = "N/A"
submddl = "Feb 6, 2018"
notidue = "Apr 18, 2018"
countdown2ddl = "2018/7/11"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "PPoPP"
confsite = "https://ppopp18.sigplan.org"
when = "Feb 24-28, 2018"
absddl = "N/A"
submddl = "Aug 25, 2017"
notidue = "Dec 6, 2017"
countdown2ddl = ""
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "SPAA"
confsite = "http://spaa.acm.org/"
when = "Jul 16-18, 2018"
absddl = "Feb 6, 2018"
submddl = "Feb 13, 2018"
notidue = "Apr 18, 2018"
countdown2ddl = "2018/7/16"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "PODC"
confsite = "https://www.podc.org/"
when = "Jul 23-27, 2018"
absddl = "Feb 11, 2018"
submddl = "Feb 18, 2018"
notidue = "Apr 28, 2018"
countdown2ddl = "2018/7/23"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "DAC"
confsite = "https://dac.com"
when = "Jun 24-28, 2018"
absddl = "Nov 14, 2017"
submddl = "Nov 21, 2017"
notidue = "TBA"
countdown2ddl = "2018/7/24"
countdown2event = ""

[[params.upcoming.list]]
enable = 1
confname = "DATE"
confsite = "https://www.date-conference.com/"
when = "Mar 25-29, 2019"
absddl = "N/A"
submddl = "Sep 9, 2018"
notidue = "Nov 8, 2018"
countdown2ddl = "2018/9/9"
countdown2event = "2019/3/25"

[[params.upcoming.list]]
enable = 1
confname = "EuroSys"
confsite = "https://www.eurosys2019.org"
when = "Mar 25-28, 2018"
absddl = "Sep 24, 2019"
submddl = "Oct 1, 2018"
notidue = "21 Dec, 2018"
countdown2ddl = "2018/9/24"
countdown2event = "2019/3/25"

[[params.past.list]]
enable = -1
confname = "HPDC"
confsite = "http://www.hpdc.org/2018/"
when = "Jun 11-15, 2018"
absddl = "Jan 17, 2018"
submddl = "Jan 24, 2018"
notidue = "Mar 29, 2018"
countdown2ddl = "2018/6/11"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "ICCD"
confsite = "http://www.iccd-conf.com"
when = "Oct 7-10, 2018"
absddl = "May 18, 2018"
submddl = "May 25, 2018"
notidue = "Aug 6, 2018"
countdown2ddl = "2018/10/7"
countdown2event = "2018/10/7"

[[params.past.list]]
enable = -1
confname = "ICCAD"
confsite = "http://www.iccad2018.com"
when = "Mar 19-21, 2018"
absddl = "N/A"
submddl = "Dec 25, 2017"
notidue = "Jan 201, 2018"
countdown2ddl = ""
countdown2event = ""

[[params.past.list]]
enable = 1
confname = "HiPEAC"
confsite = "http://hipeac.net/conference"
when = "Jan 21-23, 2019"
absddl = "N/A"
submddl = "Jun 1, 2018"
notidue = "N/A"
countdown2ddl = "2018/6/1"
countdown2event = "2019/1/21"

[[params.past.list]]
enable = -1
confname = "SIGMETRICS"
confsite = "https://www.sigmetrics.org/sigmetrics2018/"
when = "Jun 18-22, 2018"
absddl = "Jul 10, 2017"
submddl = "Jul 17, 2017"
notidue = "Sep 22, 2017"
countdown2ddl = "2018/6/18"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "ICPP"
confsite = "http://www.icpp-conf.org"
when = "Aug 13-16, 2018"
absddl = "N/A"
submddl = "Apr 9, 2018"
notidue = "May 3, 2018"
countdown2ddl = "2018/8/13"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "ICS"
confsite = "http://ics2018.ict.ac.cn/#call-for-papers/"
when = "Jun 12-15, 2018"
absddl = "N/A"
submddl = "Jan 29, 2018"
notidue = "Mar 25, 2018"
countdown2ddl = "2018/6/12"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "IPDPS"
confsite = "http://www.ipdps.org/"
when = "May 21-25, 2018"
absddl = "Oct 17, 2017"
submddl = "Oct 22, 2017"
notidue = "Jan 22, 2017"
countdown2ddl = "2018/5/21"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "Performance"
confsite = "https://performance2018.sciencesconf.org/"
when = "Dec 5-7, 2018"
absddl = "May 4, 2018"
submddl = "May 11, 2018"
notidue = "July 13, 2018"
countdown2ddl = "2018/12/5"
countdown2event = "2018/12/5"

[[params.past.list]]
enable = -1
confname = "MSST"
confsite = "http://storageconference.us/"
when = "May 14-16, 2018"
absddl = "-"
submddl = "-"
notidue = "-"
countdown2ddl = "2018/5/14"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "PACT"
confsite = "http://pactconf.org/index.php"
when = "Nov 1-4, 2018"
absddl = "Apr 8, 2018"
submddl = "Apr 15, 2018"
notidue = "Jun 20, 2018"
countdown2ddl = "2018/11/1"
countdown2event = "2018/11/1"

[[params.past.list]]
enable = -1
confname = "CODES+ISSS"
confsite = "http://www.esweek.org"
when = "Sep 30 - Oct 5, 2018"
absddl = "Mar 27, 2018"
submddl = "Apr 3, 2018"
notidue = "Jul 1, 2018"
countdown2ddl = "2018/9/30"
countdown2event = "2018/9/30"

[[params.past.list]]
enable = -1
confname = "FSE/ESEC"
confsite = "https://2018.fseconference.org"
when = "Nov 4-9, 2018"
absddl = "N/A"
submddl = "Mar 9, 2018"
notidue = "Jun 11, 2018"
countdown2ddl = "2018/11/4"
countdown2event = "2018/11/4"

[[params.past.list]]
enable = -1
confname = "OOPSLA"
confsite = "https://conf.researchr.org/track/splash-2018/splash-2018-OOPSLA"
when = "Nov 4-9, 2018"
absddl = "N/A"
submddl = "Apr 16, 2018"
notidue = "Jun 10, 2018"
countdown2ddl = "2018/11/4"
countdown2event = "2018/11/4"

[[params.past.list]]
enable = -1
confname = "ICSE"
confsite = "https://www.icse2018.org/"
when = "May 27 - Jun 3, 2018"
absddl = "N/A"
submddl = "Oct 10, 2017"
notidue = "Nov 20, 2017"
countdown2ddl = "2018/5/27"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "OSDI"
confsite = "https://www.usenix.org/conference/osdi18/"
when = "Oct 8-10, 2018"
absddl = "Apr 26, 2018"
submddl = "May 3, 2018"
notidue = "Jul 24, 2018"
countdown2ddl = "2018/10/8"
countdown2event = "2018/10/8"

[[params.past.list]]
enable = -1
confname = "PLDI"
confsite = "http://pldi18.sigplan.org"
when = "Jun 20-22, 2018"
absddl = "N/A"
submddl = "Nov 16, 2017"
notidue = "Feb 13, 2018"
countdown2ddl = "2018/6/20"
countdown2event = ""

[[params.past.list]]
enable = 1
confname = "POPL"
confsite = "https://popl19.sigplan.org/"
when = "Jan 6-26, 2019"
absddl = "N/A"
submddl = "Jul 11, 2018"
notidue = "Sep 17, 2018"
countdown2ddl = "2018/7/11"
countdown2event = "2019/1/6"

[[params.upcoming.list]]
enable = 1
confname = "SOSP"
confsite = "https://www.sigops.org/sosp/sosp19"
when = "2019"
absddl = "Mar 2019"
submddl = "TBA"
notidue = "TBA"
countdown2ddl = "2019/4/14"
countdown2event = "2019/10/28"

[[params.upcoming.list]]
enable = 1
confname = "HotOS"
confsite = ""
when = "2019"
absddl = "TBA"
submddl = "TBA"
notidue = "TBA"
countdown2ddl = "2019/1/1"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "SIGMOD"
confsite = "https://sigmod2018.org/"
when = "Jun 10-15, 2018"
absddl = "Jul 6, 2017"
submddl = "Jul 13, 2017"
notidue = "Nov 3, 2017"
countdown2ddl = "2018/6/10"
countdown2event = ""

[[params.past.list]]
enable = -1
confname = "VLDB"
confsite = "http://vldb2018.lncc.br/"
when = "Aug 27-31, 2018"
absddl = "Mar 1, 2018"
submddl = "Mar 1, 2018"
notidue = "Apr 15, 2018"
countdown2ddl = "2018/8/27"
countdown2event = "2018/8/27"

[[params.past.list]]
enable = -1
confname = "ICDE"
confsite = "https://icde2018.org/"
when = "Apr 16-20, 2018"
absddl = "Sep 22, 2017"
submddl = "Sep 29, 2017"
notidue = "Dec 22, 2017"
countdown2ddl = ""
countdown2event = ""

[[params.past.list]]
enable = 1
confname = "CIDR"
confsite = "http://cidrdb.org/cidr2019/"
when = "Jan 13-16, 2019"
absddl = "N/A"
submddl = "Aug 20, 2018"
notidue = "Oct 22, 2018"
countdown2ddl = "2018/8/20"
countdown2event = "2019/1/13"

[[params.past.list]]
enable = -1
confname = "EMSOFT"
confsite = "http://www.esweek.org"
when = "Sep 30 - Oct 5, 2018"
absddl = "Mar 27, 2018"
submddl = "Apr 3, 2018"
notidue = "Jul 1, 2018"
countdown2ddl = "2018/9/30"
countdown2event = "2018/9/30"

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://atom.im/ccf)"

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im/)."

