# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

[params]
# Meta
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu WAN"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured Call"
year = "2019"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
#final = "Final Version"
countdown = "Countdown" # yyyy/mm/dd hh:mm (Asia/Shanghai)

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming Calls"
year = "2020"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive Calls"
year = "2019"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "ClosingClosing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past Calls"
year = "2019"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# [ONE] highlight item
[[params.highlight.list]]
enable = 1
name = "ICCD"
rank="B"
site = "http://www.iccd-conf.com"
when = "Nov 17-20, 2019"
open = "Nov 17, 2019"
close= "Nov 20, 2019"
absddl = "Jun 21, 2019"
submddl = "Jun 28, 2019"
notidue = "Sep 9, 2019"
countdown = "2019-06-22 19:59:59"

[[params.upcoming.list]]
enable = 1
name = "ASPLOS"
rank="A"
site = "https://asplos-conference.org/"
when = "March 16-20, 2020"
open = "Mar 16, 2020"
close= "Mar 20, 2020"
absddl = "Aug 9, 2019"
submddl = "Aug 16, 2019"
notidue = "Nov 20, 2019"
countdownd = "2019/8/9"
countdownc = "2020/3/16"

[[params.upcoming.list]]
enable = -1
name = "FAST"
rank="A"
site = "https://www.usenix.org/conference/fast20/call-for-papers"
when = "Feb 24-27, 2019"
open = "Feb 24, 2019"
close= "Feb 27, 2019"
absddl = "N/A"
submddl = "Sep 26, 2019"
notidue = "Dec 11, 2019"
countdownd = "2019/9/26"
countdownc = "2020/2/24"

[[params.upcoming.list]]
enable = -1
name = "HPCA"
rank="A"
site = "https://www.hpca-conf.org/2020/"
when = "Feb 22-26, 2020"
open = "Feb 22, 2020"
close= "Feb 26, 2020"
absddl = "Jul 30, 2019"
submddl = "Aug 6, 2019"
notidue = "Nov 6, 2019"
countdownd = "2019/7/30"
countdownc = "2020/2/22"

[[params.current.list]]
enable = -1
name = "ISCA"
rank="A"
site = "http://iscaconf.org/isca2019"
when = "Jun 22-26, 2019"
open = "Jun 22, 2019"
close= "Jun 26, 2019"
absddl = "Dec 3, 2018"
submddl = "Dec 7, 2018"
notidue = "Mar 15, 2019"
countdownd = "2018/12/3"
countdownc = "2019/6/22"

[[params.current.list]]
enable = -1
name = "MICRO"
rank="A"
site = "https://www.microarch.org/micro52/"
when = "Oct 12-16, 2019"
open = "Oct 12, 2019"
close= "Oct 16, 2019"
absddl = "Mar 29, 2019"
submddl = "Apr 5, 2019"
notidue = "Jul 27, 2019"
countdownd = "2019/3/30"
countdownc = "2019/10/20"

[[params.current.list]]
enable = -1
name = "SC"
rank="A"
site = "https://sc19.supercomputing.org"
when = "Nov 17-22, 2019"
open = "Nov 17, 2019"
close= "Nov 22, 2019"
absddl = "Apr 2, 2019"
submddl = "Apr 10, 2019"
notidue = "Jun 15, 2019"
countdownd = "2019/4/10"
countdownc = "2019/11/11"

[[params.current.list]]
enable = -1
name = "USENIX ATC"
rank="A"
site = "https://www.usenix.org/conference/atc19/call-for-papers"
when = "Jul 10-12, 2019"
open = "Jul 10, 2019"
close= "Jul 12, 2019"
absddl = "N/A"
submddl = "Jan 10, 2019"
notidue = "Apr 16, 2019"
countdownd = "2019/1/10"
countdownc = "2019/7/10"

[[params.past.list]]
enable = -1
name = "PPoPP"
rank="A"
site = "https://ppopp19.sigplan.org"
when = "Feb 16-20, 2019"
open = "Feb 16, 2019"
close= "Feb 20, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = ""
countdownc = "2019/2/16"

[[params.current.list]]
enable = -1
name = "SPAA"
rank="B"
site = "http://spaa.acm.org/"
when = "Jun 22-24, 2019"
open = "Jun 22, 2019"
close= "Jun 24, 2019"
absddl = "Jan 8, 2019"
submddl = "Jan 11, 2019"
notidue = "Mar 11, 2019"
countdownd = "2019/1/8"
countdownc = "2019/6/22"

[[params.current.list]]
enable = -1
name = "PODC"
rank="B"
site = "https://www.podc.org/"
when = "Jul 29-Aug 2, 2019"
open = "Jul 29, 2019"
close= "Aug 2, 2019"
absddl = "N/A"
submddl = "Feb 18, 2019"
notidue = "May 5, 2019"
countdownd = "2019/2/18"
countdownc = "2019/7/29"

[[params.current.list]]
enable = -1
name = "DAC"
rank="A"
site = "https://dac.com"
when = "Jun 2-6, 2019"
open = "Jun 2, 2019"
close= "Jun 6, 2019"
absddl = "Nov 20, 2018"
submddl = "Nov 27, 2018"
notidue = "Feb 14, 2019"
countdownd = "2018/11/20"
countdownc = "2019/6/2"

[[params.past.list]]
enable = -1
name = "DATE"
rank="B"
site = "https://www.date-conference.com/"
when = "Mar 25-29, 2019"
open = "Mar 25, 2019"
close= "Mar 29, 2019"
absddl = "N/A"
submddl = "Sep 9, 2018"
notidue = "Nov 8, 2018"
countdownd = "2018/9/9"
countdownc = "2019/3/25"

[[params.past.list]]
enable = -1
name = "EuroSys"
rank="B"
site = "https://www.eurosys2019.org"
when = "Mar 25-28, 2018"
open = "Mar 25, 2018"
close= "Mar 28, 2018"
absddl = "Sep 24, 2019"
submddl = "Oct 1, 2018"
notidue = "21 Dec, 2018"
countdownd = "2018/9/24"
countdownc = "2019/3/25"

[[params.current.list]]
enable = -1
name = "HPDC"
rank="B"
site = "http://www.hpdc.org/2019/"
when = "Jun 24-28, 2019"
open = "Jun 24, 2019"
close= "Jun 28, 2019"
absddl = "Jan 16, 2019"
submddl = "Jan 23, 2019"
notidue = "Mar 25, 2019"
countdownd = "2019/1/16"
countdownc = "2019/6/24"

[[params.upcoming.list]]
enable = 0
name = "ICCD"
rank="B"
site = "http://www.iccd-conf.com"
when = "Nov 17-20, 2019"
open = "Nov 17, 2019"
close= "Nov 20, 2019"
absddl = "Jun 21, 2019"
submddl = "Jun 28, 2019"
notidue = "Sep 9, 2019"
countdownd = "2019/6/21"
countdownc = "2019/11/17"

[[params.current.list]]
enable = -1
name = "ICCAD"
rank="B"
site = "http://www.iccad-conf.com"
when = "Jul 2-4, 2019"
open = "Jul 2, 2019"
close= "Jul 4, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = ""
countdownc = "2019/7/2"

[[params.past.list]]
enable = 1
name = "HiPEAC"
rank="B"
site = "http://hipeac.net/conference"
when = "Jan 21-23, 2019"
open = "Jan 21, 2019"
close= "Jan 23, 2019"
absddl = "N/A"
submddl = "Jun 1, 2018"
notidue = "N/A"
countdownd = "2018/6/1"
countdownc = "2019/1/21"

[[params.current.list]]
enable = -1
name = "SIGMETRICS"
rank="B"
site = "https://www.sigmetrics.org/sigmetrics2019"
when = "Jun 24-28, 2019"
open = "Jun 24, 2019"
close= "Jun 28, 2019"
absddl = "Oct 22, 2018"
submddl = "Oct 29, 2018"
notidue = "Dec 17, 2018"
countdownd = "2018/10/22"
countdownc = "2019/6/24"

[[params.current.list]]
enable = -1
name = "ICPP"
rank="B"
site = "http://www.icpp-conf.org"
when = "Aug 5-8, 2019"
open = "Aug 5, 2019"
close= "Aug 8, 2019"
absddl = "N/A"
submddl = "Apr 15, 2019"
notidue = "May 17, 2019"
countdownd = "2019/4/15"
countdownc = "2019/8/5"

[[params.current.list]]
enable = -1
name = "ICS"
rank="B"
site = "https://ics19.eecis.udel.edu/"
when = "Jun 26-28, 2019"
open = "Jun 26, 2019"
close= "Jun 28, 2019"
absddl = "Jan 25, 2019"
submddl = "Feb 1, 2019"
notidue = "Mid Apr, 2019"
countdownd = "2019/1/25"
countdownc = "2019/6/26"

[[params.upcoming.list]]
enable = -1
name = "IPDPS"
rank="B"
site = "http://www.ipdps.org/"
when = "May 18-22, 2020"
open = "May 18, 2020"
close= "May 22, 2020"
absddl = "Oct 7, 2019"
submddl = "Oct 14, 2019"
notidue = "Dec 9, 2019"
countdownd = "2019/10/7"
countdownc = "2020/5/18"

[[params.current.list]]
enable = -1
name = "Performance"
rank="B"
site = "https://www.sigmetrics.org/sigmetrics2019"
when = "Jun 24-28, 2019"
open = "Jun 24, 2019"
close= "Jun 28, 2019"
absddl = "Oct 22, 2018"
submddl = "Oct 29, 2018"
notidue = "Dec 17, 2018"
countdownd = "2018/10/22"
countdownc = "2019/6/24"

[[params.past.list]]
enable = -1
name = "MSST"
rank="B"
site = "http://storageconference.us/"
when = "May 20-24, 2019"
open = "May 20, 2019"
close= "May 24, 2019"
absddl = "N/A"
submddl = "Jan 7, 2019"
notidue = "Feb 15, 2019"
countdownd = "2019/1/7"
countdownc = "2019/5/20"

[[params.current.list]]
enable = -1
name = "PACT"
rank="B"
site = "http://hpc.pnl.gov/pact19/"
when = "Sep 23-26, 2019"
open = "Sep 23, 2019"
close= "Sep 26, 2019"
absddl = "Apr 11, 2019"
submddl = "Apr 15, 2019"
notidue = "Jun 8, 2019"
countdownd = "2019/4/11"
countdownc = "2019/9/23"

[[params.current.list]]
enable = -1
name = "CODES+ISSS"
rank="B"
site = "http://www.esweek.org"
when = "Oct 13-18, 2019"
open = "Oct 13, 2019"
close= "Oct 18, 2019"
absddl = "Apr 5, 2019"
submddl = "Apr 12, 2019"
notidue = "Jul 10, 2019"
countdownd = "2019/4/5"
countdownc = "2019/10/13"

[[params.current.list]]
enable = -1
name = "FSE/ESEC"
rank="A"
site = "https://esec-fse19.ut.ee/"
when = "Aug 26-30, 2019"
open = "Aug 26, 2019"
close= "Aug 30, 2019"
absddl = "N/A"
submddl = "Feb 20, 2019"
notidue = "May 27, 2019"
countdownd = "2019/2/20"
countdownc = "2019/8/26"

[[params.current.list]]
enable = -1
name = "OOPSLA"
rank="A"
site = "https://2019.splashcon.org/track/splash-2019-oopsla"
when = "Oct 20-25, 2019"
open = "Oct 20, 2019"
close= "Oct 25, 2019"
absddl = "N/A"
submddl = "Apr 5, 2019"
notidue = "Jul 1, 2019"
countdownd = "2019/11/4"
countdownc = "2019/11/4"

[[params.past.list]]
enable = -1
name = "ICSE"
rank="A"
site = "https://2019.icse-conferences.org"
when = "May 25-31, 2019"
open = "May 25, 2019"
close= "May 31, 2019"
absddl = "N/A"
submddl = "Oct 1, 2018"
notidue = "Dec 12, 2018"
countdownd = "2018/10/1"
countdownc = "2019/5/25"

[[params.past.list]]
enable = -1
name = "OSDI*"
rank="A"
site = "https://www.usenix.org/conference/osdi18/"
when = "Oct 8-10, 2018"
open = "Oct 8, 2018"
close= "Oct 10, 2018"
absddl = "Apr 26, 2018"
submddl = "May 3, 2018"
notidue = "Jul 24, 2018"
countdownd = "2018/10/8"
countdownc = "2018/10/8"

[[params.current.list]]
enable = -1
name = "PLDI"
rank="A"
site = "http://pldi19.sigplan.org"
when = "Jun 22-26, 2019"
open = "Jun 22, 2019"
close= "Jun 26, 2019"
absddl = "N/A"
submddl = "Nov 16, 2018"
notidue = "Feb 15, 2018"
countdownd = "2018/11/22"
countdownc = "2019/6/22"

[[params.past.list]]
enable = -1
name = "POPL"
rank="A"
site = "https://popl19.sigplan.org/"
when = "Jan 13-19, 2019"
open = "Jan 13, 2019"
close= "Jan 19, 2019"
absddl = "N/A"
submddl = "Jul 11, 2018"
notidue = "Sep 17, 2018"
countdownd = "2018/7/11"
countdownc = "2019/1/6"

[[params.current.list]]
enable = -1
name = "SOSP"
rank="A"
site = "https://www.sigops.org/sosp/sosp19"
when = "Oct 27-30, 2019"
open = "Oct 27, 2019"
close= "Oct 30, 2019"
absddl = "Apr 17, 2019"
submddl = "Apr 24, 2019"
notidue = "Jul 8/22, 2019"
countdownd = "2019/4/17"
countdownc = "2019/10/27"

[[params.past.list]]
enable = -1
name = "HotOS"
rank="B"
site = "https://www.sigops.org/2018/hotos2019/"
when = "May 12-15, 2019"
open = "May 12, 2019"
close= "May 15, 2019"
absddl = "N/A"
submddl = "Jan 17, 2019"
notidue = "Mar 11"
countdownd = "2019/1/17"
countdownc = "2019/5/12"

[[params.current.list]]
enable = -1
name = "SIGMOD"
rank="A"
site = "https://sigmod2019.org/"
when = "Jun 30-Jul 5, 2019"
open = "Jun 30, 2019"
close= "Jul 5, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = ""
countdownc = "2019/6/30"

[[params.current.list]]
enable = -1
name = "VLDB"
rank="A"
site = "http://vldb.org/2019/"
when = "Aug 26-30, 2018"
open = "Aug 26, 2018"
close= "Aug 30, 2018"
absddl = "Mar 1, 2019"
submddl = "Mar 1, 2019"
notidue = "Apr 15, 2019"
countdownd = "2019/3/1"
countdownc = "2019/8/26"

[[params.upcoming.list]]
enable = -1
name = "ICDE-1"
rank="A"
site = "https://www.utdallas.edu/icde/"
when = "Apr 20-24, 2020"
open = "Apr 20, 2020"
close= "Apr 24, 2020"
absddl = "Jun 8, 2019"
submddl = "Jun 15, 2019"
notidue = "Aug 10, 2019"
countdownd = "2019/6/8"
countdownc = "2020/4/20"

[[params.upcoming.list]]
enable = -1
name = "ICDE-2"
rank="A"
site = "https://www.utdallas.edu/icde/"
when = "Apr 20-24, 2020"
open = "Apr 20, 2020"
close= "Apr 24, 2020"
absddl = "Oct 8, 2019"
submddl = "Oct 15, 2019"
notidue = "Dec 14, 2019"
countdownd = "2019/10/8"
countdownc = "2020/4/20"

[[params.past.list]]
enable = 1
name = "CIDR"
rank="A"
site = "http://cidrdb.org/cidr2019/"
when = "Jan 13-16, 2019"
open = "Jan 13, 2019"
close= "Jan 16, 2019"
absddl = "N/A"
submddl = "Aug 20, 2018"
notidue = "Oct 22, 2018"
countdownd = "2018/8/20"
countdownc = "2019/1/13"

[[params.current.list]]
enable = -1
name = "EMSOFT"
rank="B"
site = "http://www.esweek.org"
when = "Oct 13-18, 2019"
open = "Oct 13, 2019"
close= "Oct 18, 2019"
absddl = "Apr 5, 2019"
submddl = "Apr 12, 2019"
notidue = "Jul 10, 2019"
countdownd = "2019/4/5"
countdownc = "2019/10/13"

[[params.current.list]]
enable = -1
name = "NVMSA"
rank="-"
site = "https://nvmsa2019.github.io/index"
when = "Aug 18-21, 2019"
open = "Aug 18, 2019"
close= "Aug 21, 2019"
absddl = "Apr 12, 2019"
submddl = "Apr 19, 2019"
notidue = "May 20, 2019"
countdownd = "2019/4/5"
countdownc = "2019/8/18"

[[params.current.list]]
enable = -1
name = "HotStorage"
rank="-"
site = "https://www.usenix.org/conference/hotstorage19"
when = "Jul 8-9, 2019"
open = "Jul 8, 2019"
close= "Jul 9, 2019"
absddl = "N/A"
submddl= "Mar 13, 2019"
notidue = "Apr 17, 2019"
countdownd = "2019/3/13"
countdownc = "2019/7/8"

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im)"

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

