# Page settings
baseurl = "https://cfp.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im)"

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured Call"
year = "2019"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown (HKT)" # yyyy/mm/dd hh:mm:ss (Asia/Hong_Kong)

# Upcoming section
# enable:
#  0 - disable
#  1 - nextyear (2021)
# -1 - year (2020)
[params.upcoming]
enable = true
title = "Upcoming Calls"
year = "2020"
nextyear = "2021"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
# enable:
#  0 - disable
#  1 - nextyear (2020)
# -1 - year (2019)
[params.current]
enable = true
title = "Inactive Calls"
year = "2019"
nextyear = "2020"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "ClosingClosing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
# enable:
#  0 - disable
#  1 - lastyear (2018)
# -1 - year (2019)
[params.past]
enable = true
title = "Past Calls"
year = "2019"
lastyear = "2018"
name = "Name"
rank="Rank"
when = "When"
open = "Opening"
close= "Closing"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

# [ONE] highlight item
[[params.highlight.list]]
enable = 1
name = "ASPLOS"
rank = "A"
site = "https://asplos-conference.org/"
open = "2020-03-16"
close = "2020-03-20"
absddl = "2019-08-09"
submddl = "2019-08-16"
notidue = "2019-11-20"
countdown = "2019-08-17 07:59:59"

[[params.cfp.list]]
enable = 0
name = "ASPLOS"
rank = "A"
site = "https://asplos-conference.org/"
open = "2020-03-16"
close = "2020-03-20"
absddl = "2019-08-09"
submddl = "2019-08-16"
notidue = "2019-11-20"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast20/call-for-papers"
open = "2020-02-24"
close = "2020-02-27"
absddl = "N/A"
submddl = "2019-09-26"
notidue = "2019-12-11"

[[params.cfp.list]]
enable = 1
name = "HPCA"
rank = "A"
site = "https://www.hpca-conf.org/2020/"
open = "2020-02-22"
close = "2020-02-26"
absddl = "2019-07-30"
submddl = "2019-08-06 17:00:00"
notidue = "2019-11-06"

[[params.cfp.list]]
enable = 1
name = "ISCA"
rank = "A"
site = "http://iscaconf.org/isca2019"
open = "2019-06-22"
close = "2019-06-26"
absddl = "2018-12-03"
submddl = "2018-12-07"
notidue = "2019-03-15"

[[params.cfp.list]]
enable = 1
name = "MICRO"
rank = "A"
site = "https://www.microarch.org/micro52/"
open = "2019-10-12"
close = "2019-10-16"
absddl = "2019-03-29"
submddl = "2019-04-05"
notidue = "2019-07-27"

[[params.cfp.list]]
enable = 1
name = "SC"
rank = "A"
site = "https://sc19.supercomputing.org"
open = "2019-11-17"
close = "2019-11-22"
absddl = "2019-04-02"
submddl = "2019-04-10"
notidue = "2019-06-15"

[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc20/call-for-papers"
open = "2020-07-15"
close = "2020-07-17"
absddl = "N/A"
submddl = "2020-01-15"
notidue = "2020-04-24"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp20.sigplan.org"
open = "2020-02-22"
close = "2020-02-26"
absddl = "2019-07-31"
submddl = "2019-08-06"
notidue = "2019-11-19"

[[params.cfp.list]]
enable = 1
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2019-06-22"
close = "2019-06-24"
absddl = "2019-01-08"
submddl = "2019-01-11"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 1
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2019-07-29"
close = "2019-08-02"
absddl = "N/A"
submddl = "2019-02-18"
notidue = "2019-05-05"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2019-06-02"
close = "2019-06-06"
absddl = "2018-11-20"
submddl = "2018-11-27"
notidue = "2019-02-14"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2020-03-09"
close = "2020-03-13"
absddl = "N/A"
submddl = "2019-09-08"
notidue = "2019-11-07"

[[params.cfp.list]]
enable = 1
name = "EuroSys"
rank = "B"
site = "https://www.eurosys2020.org"
open = "2020-04-27"
close = "2020-04-30"
absddl = "N/A"
submddl = "2019-11-04"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 1
name = "HPDC"
rank = "B"
site = "http://www.hpdc.org/2019/"
open = "2019-06-24"
close = "2019-06-28"
absddl = "2019-01-16"
submddl = "2019-01-23"
notidue = "2019-03-25"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2019-11-17"
close = "2019-11-20"
absddl = "2019-06-28"
submddl = "2019-07-07"
notidue = "2019-09-09"

[[params.cfp.list]]
enable = 1
name = "ICCAD"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2019-07-02"
close = "2019-07-04"
absddl = "N/A"
submddl = "2019-07-02"
notidue = "2019-07-02"

[[params.cfp.list]]
enable = 1
name = "HiPEAC"
rank = "B"
site = "http://hipeac.net/conference"
open = "2020-01-20"
close = "2020-01-22"
absddl = "N/A"
submddl = "2019-06-01"
notidue = "2019-11-15"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2019"
open = "2019-06-24"
close = "2019-06-28"
absddl = "2018-10-22"
submddl = "2018-10-29"
notidue = "2018-12-17"

[[params.cfp.list]]
enable = 1
name = "ICPP"
rank = "B"
site = "http://www.icpp-conf.org"
open = "2019-08-05"
close = "2019-08-08"
absddl = "N/A"
submddl = "2019-04-15"
notidue = "2019-05-17"

[[params.cfp.list]]
enable = 1
name = "ICS"
rank = "B"
site = "https://ics19.eecis.udel.edu/"
open = "2019-06-26"
close = "2019-06-28"
absddl = "2019-01-25"
submddl = "2019-02-01"
notidue = "2019-04-01"

[[params.cfp.list]]
enable = 1
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2020-05-18"
close = "2020-05-22"
absddl = "2019-10-07"
submddl = "2019-10-14"
notidue = "2019-12-09"

[[params.cfp.list]]
enable = 1
name = "Performance"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2019"
open = "2019-06-24"
close = "2019-06-28"
absddl = "2018-10-22"
submddl = "2018-10-29"
notidue = "2018-12-17"

[[params.cfp.list]]
enable = 1
name = "MSST*"
rank = "B"
site = "http://storageconference.us/"
open = "2020-05-04"
close = "2020-05-08"
absddl = "N/A"
submddl = "2020-01-07"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 1
name = "PACT"
rank = "B"
site = "http://hpc.pnl.gov/pact19/"
open = "2019-09-23"
close = "2019-09-26"
absddl = "2019-04-11"
submddl = "2019-04-15"
notidue = "2019-06-08"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2019-10-13"
close = "2019-10-18"
absddl = "2019-04-05"
submddl = "2019-04-12"
notidue = "2019-07-10"

[[params.cfp.list]]
enable = 1
name = "FSE/ESEC"
rank = "A"
site = "https://esec-fse19.ut.ee/"
open = "2019-08-26"
close = "2019-08-30"
absddl = "N/A"
submddl = "2019-02-20"
notidue = "2019-05-27"

[[params.cfp.list]]
enable = 1
name = "OOPSLA"
rank = "A"
site = "https://2019.splashcon.org/track/splash-2019-oopsla"
open = "2019-10-20"
close = "2019-10-25"
absddl = "N/A"
submddl = "2019-04-05"
notidue = "2019-07-01"

[[params.cfp.list]]
enable = 1
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2020"
open = "2020-05-23"
close = "2020-05-29"
absddl = "N/A"
submddl = "2019-08-23"
notidue = "2019-12-09"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi18/"
open = "2018-10-08"
close = "2018-10-10"
absddl = "2018-04-26"
submddl = "2018-05-03"
notidue = "2018-07-24"

[[params.cfp.list]]
enable = 1
name = "PLDI"
rank = "A"
site = "http://pldi19.sigplan.org"
open = "2019-06-22"
close = "2019-06-26"
absddl = "N/A"
submddl = "2018-11-16"
notidue = "2018-02-15"

[[params.cfp.list]]
enable = 1
name = "POPL"
rank = "A"
site = "https://popl20.sigplan.org/"
open = "2020-01-19"
close = "2020-01-25"
absddl = "N/A"
submddl = "2019-07-10"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 1
name = "SOSP"
rank = "A"
site = "https://www.sigops.org/sosp/sosp19"
open = "2019-10-27"
close = "2019-10-30"
absddl = "2019-04-17"
submddl = "2019-04-24"
notidue = "2019-07-22"

[[params.cfp.list]]
enable = 1
name = "HotOS"
rank = "B"
site = "https://www.sigops.org/2018/hotos2019/"
open = "2019-05-12"
close = "2019-05-15"
absddl = "N/A"
submddl = "2019-01-17"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 1
name = "SIGMOD"
rank = "A"
site = "https://sigmod2019.org/"
open = "2019-06-30"
close = "2019-07-05"
absddl = "N/A"
submddl = "2019-06-30"
notidue = "2019-06-30"

[[params.cfp.list]]
enable = 1
name = "VLDB"
rank = "A"
site = "http://vldb.org/2019/"
open = "2019-08-26"
close = "2019-08-30"
absddl = "2019-03-01"
submddl = "2019-03-01"
notidue = "2019-04-15"

[[params.cfp.list]]
enable = 1
name = "ICDE-1"
rank = "A"
site = "https://www.utdallas.edu/icde/"
open = "2020-04-20"
close = "2020-04-24"
absddl = "2019-06-08"
submddl = "2019-06-15"
notidue = "2019-08-10"

[[params.cfp.list]]
enable = 1
name = "ICDE-02"
rank = "A"
site = "https://www.utdallas.edu/icde/"
open = "2020-04-20"
close = "2020-04-24"
absddl = "2019-10-08"
submddl = "2019-10-15"
notidue = "2019-12-14"

[[params.cfp.list]]
enable = 1
name = "CIDR"
rank = "A"
site = "http://cidrdb.org/cidr2020/"
open = "2020-01-12"
close = "2020-01-15"
absddl = "N/A"
submddl = "2019-08-23"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 1
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2019-10-13"
close = "2019-10-18"
absddl = "2019-04-05"
submddl = "2019-04-12"
notidue = "2019-07-10"

[[params.cfp.list]]
enable = 1
name = "NVMSA"
rank = "-"
site = "https://nvmsa2019.github.io/index"
open = "2019-08-18"
close = "2019-08-21"
absddl = "2019-04-12"
submddl = "2019-04-19"
notidue = "2019-05-20"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = "-"
site = "https://www.usenix.org/conference/hotstorage19"
open = "2019-07-08"
close = "2019-07-09"
absddl = "N/A"
submddl = "2019-03-03"
notidue = "2019-04-17"

[[params.cfp.list]]
enable = 1
name = "SysML"
rank = "-"
site = "https://systemsandml.org"
open = "2020-03-02"
close = "2020-03-04"
absddl = "N/A"
submddl = "2019-09-09"
notidue = "2020-01-03"
