# Page settings
baseurl = "http://www.atom.im/"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

[blackfriday]
fractions = false
hrefTargetBlank = true

[params]
# Meta
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu WAN"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected Call for Papers in computer architecture & system fields."

# Highlight section
[params.highlight]
enable = true
title = "Highlight"
year = "2019"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
#final = "Final Version"
countdown = "Countdown" # yyyy/mm/dd hh:mm (Asia/Shanghai)

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming Calls"
year = "2019"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive Calls"
year = "2019"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past Calls"
year = "2019"
confname = "Name"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# [ONE] highlight item
[[params.highlight.list]]
enable = 1
confname = "MICRO"
confsite = "https://www.microarch.org/micro52/"
when = "Oct, 2019"
absddl = "TBA"
submddl = "TBA"
notidue = "TBA"
countdown = "2019-03-31 23:59:59"

[[params.current.list]]
enable = -1
confname = "ASPLOS"
confsite = "https://asplos-conference.org/"
when = "Apr 13-17, 2019"
absddl = "Jul 31, 2018"
submddl = "Aug 7, 2018"
notidue = "Nov 7, 2018"
countdownd = "2018/7/31"
countdownc = "2019/4/13"

[[params.current.list]]
enable = -1
confname = "FAST"
confsite = "https://www.usenix.org/conference/fast19/call-for-papers"
when = "Feb 25-28, 2019"
absddl = "N/A"
submddl = "Sep 26, 2018"
notidue = "Dec 11, 2018"
countdownd = "2018/9/26"
countdownc = "2019/2/25"

[[params.current.list]]
enable = -1
confname = "HPCA"
confsite = "http://hpca2019.seas.gwu.edu/"
when = "Feb 16-20, 2019"
absddl = "Jul 27, 2018"
submddl = "Aug 3, 2018"
notidue = "Nov 6, 2018"
countdownd = "2018/7/27"
countdownc = "2019/2/16"

[[params.upcoming.list]]
enable = 0
confname = "ISCA"
confsite = "http://iscaconf.org/isca2019"
when = "Jun 22-26, 2019"
absddl = "Nov 14, 2018"
submddl = "TBA"
notidue = "TBA"
countdownd = "2018/11/14"
countdownc = "2019/6/22"

[[params.upcoming.list]]
enable = 0
confname = "MICRO"
confsite = "https://www.microarch.org/micro52/"
when = "Oct, 2019"
absddl = "TBA"
submddl = "TBA"
notidue = "TBA"
countdownd = "2019/3/30"
countdownc = "2019/10/20"

[[params.upcoming.list]]
enable = 1
confname = "SC"
confsite = "https://sc19.supercomputing.org"
when = "Nov 17-22, 2019"
absddl = "Apr 2, 2019"
submddl = "Apr 10, 2019"
notidue = "Jun 15, 2019"
countdownd = "2019/4/10"
countdownc = "2019/11/11"

[[params.current.list]]
enable = -1
confname = "USENIX ATC"
confsite = "https://www.usenix.org/conference/atc19/call-for-papers"
when = "Jul 10-12, 2019"
absddl = "N/A"
submddl = "Jan 10, 2019"
notidue = "Apr 16, 2019"
countdownd = "2019/1/10"
countdownc = "2019/7/10"

[[params.current.list]]
enable = -1
confname = "PPoPP"
confsite = "https://ppopp19.sigplan.org"
when = "Feb 16-20, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = ""
countdownc = "2019/2/16"

[[params.current.list]]
enable = -1
confname = "SPAA"
confsite = "http://spaa.acm.org/"
when = "Jun 22-24, 2019"
absddl = "Jan 8, 2019"
submddl = "Jan 11, 2019"
notidue = "Mar 11, 2019"
countdownd = "2019/1/8"
countdownc = "2019/6/22"

[[params.upcoming.list]]
enable = -1
confname = "PODC"
confsite = "https://www.podc.org/"
when = "Jul 29-Aug 2, 2019"
absddl = "N/A"
submddl = "Feb 18, 2019"
notidue = "May 5, 2019"
countdownd = "2019/2/18"
countdownc = "2019/7/29"

[[params.current.list]]
enable = -1
confname = "DAC"
confsite = "https://dac.com"
when = "Jun 2-6, 2019"
absddl = "Nov 20, 2018"
submddl = "Nov 27, 2018"
notidue = "Feb 14, 2019"
countdownd = "2018/11/20"
countdownc = "2019/6/2"

[[params.current.list]]
enable = -1
confname = "DATE"
confsite = "https://www.date-conference.com/"
when = "Mar 25-29, 2019"
absddl = "N/A"
submddl = "Sep 9, 2018"
notidue = "Nov 8, 2018"
countdownd = "2018/9/9"
countdownc = "2019/3/25"

[[params.current.list]]
enable = -1
confname = "EuroSys"
confsite = "https://www.eurosys2019.org"
when = "Mar 25-28, 2018"
absddl = "Sep 24, 2019"
submddl = "Oct 1, 2018"
notidue = "21 Dec, 2018"
countdownd = "2018/9/24"
countdownc = "2019/3/25"

[[params.current.list]]
enable = -1
confname = "HPDC"
confsite = "http://www.hpdc.org/2019/"
when = "Jun 24-28, 2019"
absddl = "Jan 16, 2019"
submddl = "Jan 23, 2019"
notidue = "Mar 25, 2019"
countdownd = "2019/1/16"
countdownc = "2019/6/24"

[[params.upcoming.list]]
enable = -1
confname = "ICCD"
confsite = "http://www.iccd-conf.com"
when = "Nov 17-20, 2019"
absddl = "Jun 21, 2019"
submddl = "Jun 28, 2019"
notidue = "Sep 9, 2019"
countdownd = "2019/6/21"
countdownc = "2019/11/17"

[[params.current.list]]
enable = -1
confname = "ICCAD"
confsite = "http://www.iccad-conf.com"
when = "Jul 2-4, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = ""
countdownc = "2019/7/2"

[[params.past.list]]
enable = 1
confname = "HiPEAC"
confsite = "http://hipeac.net/conference"
when = "Jan 21-23, 2019"
absddl = "N/A"
submddl = "Jun 1, 2018"
notidue = "N/A"
countdownd = "2018/6/1"
countdownc = "2019/1/21"

[[params.current.list]]
enable = -1
confname = "SIGMETRICS"
confsite = "https://www.sigmetrics.org/sigmetrics2019"
when = "Jun 24-28, 2019"
absddl = "Oct 22, 2018"
submddl = "Oct 29, 2018"
notidue = "Dec 17, 2018"
countdownd = "2018/10/22"
countdownc = "2019/6/24"

[[params.upcoming.list]]
enable = -1
confname = "ICPP"
confsite = "http://www.icpp-conf.org"
when = "Aug 5-8, 2019"
absddl = "N/A"
submddl = "Apr 15, 2019"
notidue = "May 17, 2019"
countdownd = "2019/4/15"
countdownc = "2019/8/5"

[[params.current.list]]
enable = -1
confname = "ICS"
confsite = "https://ics19.eecis.udel.edu/"
when = "Jun 26-28, 2019"
absddl = "Jan 25, 2019"
submddl = "Feb 1, 2019"
notidue = "Mid Apr, 2019"
countdownd = "2019/1/25"
countdownc = "2019/6/26"

[[params.current.list]]
enable = -1
confname = "IPDPS"
confsite = "http://www.ipdps.org/"
when = "May 20-24, 2019"
absddl = "Oct 8, 2018"
submddl = "Oct 15, 2018"
notidue = "Dec 10, 2018"
countdownd = "2018/10/8"
countdownc = "2019/5/20"

[[params.current.list]]
enable = -1
confname = "Performance"
confsite = "https://www.sigmetrics.org/sigmetrics2019"
when = "Jun 24-28, 2019"
absddl = "Oct 22, 2018"
submddl = "Oct 29, 2018"
notidue = "Dec 17, 2018"
countdownd = "2018/10/22"
countdownc = "2019/6/24"

[[params.current.list]]
enable = -1
confname = "MSST"
confsite = "http://storageconference.us/"
when = "May 20-24, 2019"
absddl = "N/A"
submddl = "Jan 7, 2019"
notidue = "Feb 15, 2019"
countdownd = "2019/1/7"
countdownc = "2019/5/20"

[[params.current.list]]
enable = -1
confname = "PACT"
confsite = "http://ssd.sscc.ru/conference/pact2019/"
when = "Aug 19-23, 2019"
absddl = "N/A"
submddl = "Feb 17, 2019"
notidue = "Apr 15, 2019"
countdownd = "2019/2/17"
countdownc = "2019/8/19"

[[params.upcoming.list]]
enable = -1
confname = "CODES+ISSS"
confsite = "http://www.esweek.org"
when = "Oct 13-18, 2019"
absddl = "Apr 5, 2019"
submddl = "Apr 12, 2019"
notidue = "Jul 10, 2019"
countdownd = "2019/4/5"
countdownc = "2019/10/13"

[[params.current.list]]
enable = -1
confname = "FSE/ESEC"
confsite = "https://esec-fse19.ut.ee/"
when = "Aug 26-30, 2019"
absddl = "N/A"
submddl = "Feb 20, 2019"
notidue = "May 27, 2019"
countdownd = "2019/2/20"
countdownc = "2019/8/26"

[[params.upcoming.list]]
enable = -1
confname = "OOPSLA"
confsite = "https://2019.splashcon.org/track/splash-2019-oopsla"
when = "Oct 20-25, 2019"
absddl = "N/A"
submddl = "Apr 5, 2019"
notidue = "Jul 1, 2019"
countdownd = "2019/11/4"
countdownc = "2019/11/4"

[[params.current.list]]
enable = -1
confname = "ICSE"
confsite = "https://2019.icse-conferences.org"
when = "May 25-31, 2019"
absddl = "N/A"
submddl = "Oct 1, 2018"
notidue = "Nov 14, 2017"
countdownd = "2018/10/1"
countdownc = "2019/5/25"

[[params.past.list]]
enable = -1
confname = "OSDI*"
confsite = "https://www.usenix.org/conference/osdi18/"
when = "Oct 8-10, 2018"
absddl = "Apr 26, 2018"
submddl = "May 3, 2018"
notidue = "Jul 24, 2018"
countdownd = "2018/10/8"
countdownc = "2018/10/8"

[[params.current.list]]
enable = -1
confname = "PLDI"
confsite = "http://pldi19.sigplan.org"
when = "Jun 22-26, 2019"
absddl = "N/A"
submddl = "Nov 16, 2018"
notidue = "Feb 15, 2018"
countdownd = "2018/11/22"
countdownc = "2019/6/22"

[[params.past.list]]
enable = -1
confname = "POPL"
confsite = "https://popl19.sigplan.org/"
when = "Jan 13-19, 2019"
absddl = "N/A"
submddl = "Jul 11, 2018"
notidue = "Sep 17, 2018"
countdownd = "2018/7/11"
countdownc = "2019/1/6"

[[params.upcoming.list]]
enable = 1
confname = "SOSP"
confsite = "https://www.sigops.org/sosp/sosp19"
when = "Oct 27-30, 2019"
absddl = "Apr 17, 2019"
submddl = "Apr 24, 2019"
notidue = "Jul 8/22, 2019"
countdownd = "2019/4/17"
countdownc = "2019/10/27"

[[params.current.list]]
enable = -1
confname = "HotOS"
confsite = "https://www.sigops.org/2018/hotos2019/"
when = "May 12-15, 2019"
absddl = "N/A"
submddl = "Jan 17, 2019"
notidue = "Mar 11"
countdownd = "2019/1/17"
countdownc = "2019/5/12"

[[params.current.list]]
enable = -1
confname = "SIGMOD"
confsite = "https://sigmod2019.org/"
when = "Jun 30-Jul 5, 2019"
absddl = "N/A"
submddl = "-"
notidue = "-"
countdownd = "-"
countdownc = "2019/6/30"

[[params.upcoming.list]]
enable = -1
confname = "VLDB"
confsite = "http://vldb.org/2019/"
when = "Aug 26-30, 2018"
absddl = "Mar 1, 2019"
submddl = "Mar 1, 2019"
notidue = "Apr 15, 2019"
countdownd = "2019/3/1"
countdownc = "2019/8/26"

[[params.current.list]]
enable = -1
confname = "ICDE"
confsite = "http://conferences.cis.umac.mo/icde2019"
when = "Apr 8-12, 2019"
absddl = "Sep 28, 2018"
submddl = "Oct 5, 2018"
notidue = "Dec 14, 2018"
countdownd = "2018/9/28"
countdownc = "2019/4/8"

[[params.past.list]]
enable = 1
confname = "CIDR"
confsite = "http://cidrdb.org/cidr2019/"
when = "Jan 13-16, 2019"
absddl = "N/A"
submddl = "Aug 20, 2018"
notidue = "Oct 22, 2018"
countdownd = "2018/8/20"
countdownc = "2019/1/13"

[[params.upcoming.list]]
enable = -1
confname = "EMSOFT"
confsite = "http://www.esweek.org"
when = "Oct 13-18, 2019"
absddl = "Apr 5, 2019"
submddl = "Apr 12, 2019"
notidue = "Jul 10, 2019"
countdownd = "2019/4/5"
countdownc = "2019/10/13"

[[params.upcoming.list]]
enable = 1
confname = "NVMSA"
confsite = "https://nvmsa2019.github.io/index"
when = "Aug 18-21, 2019"
absddl = "Apr 5, 2019"
submddl = "Apr 12, 2019"
notidue = "May 20, 2019"
countdownd = "2019/4/5"
countdownc = "2019/8/18"

[[params.upcoming.list]]
enable = 1
confname = "HotStorage"
confsite = "https://www.usenix.org/conference/hotstorage19"
when = "Jul 8-9, 2019"
absddl = "N/A"
submddl= "Mar 13, 2019"
notidue = "Apr 17, 2019"
countdownd = "2019/4/13"
countdownc = "2019/7/8"

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://atom.im/ccf)"

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im/)."

